INSERT INTO products (maker, model, type) VALUES ('Samsung', '121', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Samsung', '2026', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Samsung', '2625', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Samsung', '2625F', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Samsung', '430', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Asus', 'Ai3', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Asus', 'Ai5', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Asus', 'Ai7', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Asus', 'AK75', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('Asus', 'AK95 ', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('HP', 'Celeron100', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('HP', 'Celeron150', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('HP', 'EliteBook', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('HP', 'Hi3', 'PC');
INSERT INTO products (maker, model, type) VALUES ('HP', 'Hi5', 'PC');
INSERT INTO products (maker, model, type) VALUES ('HP', 'Hi7', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Canon', 'Pix62', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Canon', 'Pix82', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Canon', 'Pix95', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Canon', 'PixColor', 'printer');
INSERT INTO products (maker, model, type) VALUES ('Samsung', 'Si3', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Samsung', 'Si5', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Samsung', 'Si7', 'PC');
INSERT INTO products (maker, model, type) VALUES ('Samsung', 'Si9', 'PC');
INSERT INTO products (maker, model, type) VALUES ('HP', 'Spectre', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('Acer', 'Swift3', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('Acer', 'Swift5', 'laptop');
INSERT INTO products (maker, model, type) VALUES ('Acer', 'Swift7', 'laptop');

INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (1, 'Swift3', 2000, 4000, 320, 600, 13);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (2, 'Swift5', 2500, 8000, 500, 700, 15);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (3, 'Swift7', 3000, 12000, 750, 1100, 15);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (4, 'Spectre', 2500, 8000, 750, 1200, 15);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (5, 'Celeron150', 150, 1000, 150, 150, 14);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (6, 'Celeron100', 100, 1000, 150, 100, 14);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (7, 'AK75', 800, 2000, 250, 300, 14);
INSERT INTO laptops (code, model, speed, ram, hd, price, screen) VALUES (8, 'AK75', 1000, 2000, 250, 350, 14);

INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (1, 'Ai3', 1600, 2000, 5, '4x', 200);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (2, 'Ai3', 1800, 2000, 320, '4X', 250);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (3, 'Ai5', 1800, 2000, 320, '4X', 300);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (4, 'Ai5', 2000, 4000, 320, '8x', 350);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (5, 'Ai5', 2200, 4000, 500, '12x', 500);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (6, 'Hi3', 1800, 4000, 320, '12x', 500);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (7, 'Hi5', 2200, 8000, 500, '12x', 700);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (8, 'Hi7', 2600, 16000, 1000, '24x', 900);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (9, 'Si3', 200, 1000, 5, '4x', 30);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (10, 'Si3', 350, 1000, 15, '4x', 45);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (11, 'Si3', 400, 1000, 30, '4x', 60);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (12, 'Si3', 200, 1000, 10, '4x', 35);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (13, 'Ai5', 2000, 2000, 100, '4x', 200);
INSERT INTO pcs (code, model, speed, ram, hd, cd, price) VALUES (14, 'Ai3', 2000, 1000, 100, '4x', 200);

INSERT INTO printers (code, model, color, type, price) VALUES (1, '2026', 'y', 'laser', 150);
INSERT INTO printers (code, model, color, type, price) VALUES (2, '2625', 'y', 'laser', 200);
INSERT INTO printers (code, model, color, type, price) VALUES (3, 'Pix82', 'n', 'jet', 80);
INSERT INTO printers (code, model, color, type, price) VALUES (4, 'Pix62', 'n', 'jet', 100);
INSERT INTO printers (code, model, color, type, price) VALUES (5, 'Pix95', 'n', 'matrix', 30);
INSERT INTO printers (code, model, color, type, price) VALUES (6, '2625F', 'y', 'laser', 200);
INSERT INTO printers (code, model, color, type, price) VALUES (7, '121', 'y', 'laser', 150);
INSERT INTO printers (code, model, color, type, price) VALUES (8, 'PixColor', 'y', 'laser', 150);